apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rails-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard # Dynamic Provisioning 環境に応じて設定する
